apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-1-pv
  labels:
    type: local
spec:
  storageClassName: tb1
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/tblogs/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mytb-claim1
  name: tb-claim1
spec:
  storageClassName: tb1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
