apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-0-pv
  labels:
    type: local
spec:
  storageClassName: tb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/tbdata/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: tb-claim0
  name: tb-claim0
spec:
  storageClassName: tb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
